// Copyright 2021-2026 The Connect Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"golang.org/x/tools/go/packages"
)

// TestIsConnectStubAST checks which generated files gate the regenerate-first
// phase: protoc-gen-connect-go stubs do, while other generated files that import
// connect (a mockery mock) do not. Both are still generated code, so
// isGeneratedAST reports true for each.
func TestIsConnectStubAST(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name     string
		header   string
		wantStub bool
		wantGen  bool
	}{
		{
			name:     "connect stub",
			header:   "// Code generated by protoc-gen-connect-go. DO NOT EDIT.",
			wantStub: true,
			wantGen:  true,
		},
		{
			name:     "mockery mock",
			header:   "// Code generated by mockery. DO NOT EDIT.",
			wantStub: false,
			wantGen:  true,
		},
		{
			name:     "mockgen mock",
			header:   "// Code generated by MockGen. DO NOT EDIT.",
			wantStub: false,
			wantGen:  true,
		},
		{
			name:     "hand written",
			header:   "// Package app is hand written.",
			wantStub: false,
			wantGen:  false,
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			src := test.header + "\n\npackage app\n\nimport _ \"connectrpc.com/connect\"\n"
			file, err := parser.ParseFile(token.NewFileSet(), "x.go", src, parser.ParseComments)
			if err != nil {
				t.Fatalf("parse: %v", err)
			}
			if got := isConnectStubAST(file); got != test.wantStub {
				t.Errorf("isConnectStubAST = %v, want %v", got, test.wantStub)
			}
			if got := isGeneratedAST(file); got != test.wantGen {
				t.Errorf("isGeneratedAST = %v, want %v", got, test.wantGen)
			}
		})
	}
}

// TestIsBSRConnectModule covers which BSR modules get the @v2 advice: only the
// connect-go plugin's output (.../connectrpc/go), not other plugins under the
// same buf.build/gen/go prefix, and not non-BSR modules.
func TestIsBSRConnectModule(t *testing.T) {
	t.Parallel()
	tests := []struct {
		module string
		want   bool
	}{
		{module: "buf.build/gen/go/parca-dev/parca/connectrpc/go", want: true},
		{module: "buf.build/gen/go/acme/api/connectrpc/go", want: true},
		{module: "buf.build/gen/go/acme/api/protocolbuffers/go", want: false}, // proto messages, versioned separately
		{module: "buf.build/gen/go/acme/api/grpc/go", want: false},            // a different plugin
		{module: "github.com/grafana/pyroscope/api", want: false},             // not a BSR module
		{module: "connectrpc.com/connect", want: false},
	}
	for _, test := range tests {
		if got := isBSRConnectModule(test.module); got != test.want {
			t.Errorf("isBSRConnectModule(%q) = %v, want %v", test.module, got, test.want)
		}
	}
}

// TestCwdPattern covers the no-module fallback mapping from a root to a
// packages.Load pattern relative to the current directory, including the "..."
// wildcards a user is likely to type (e.g. "connect-go-v2-migrate ./...").
// Those must stay rooted at "./", not become a "./.../..." path that does not
// exist.
func TestCwdPattern(t *testing.T) {
	t.Parallel()
	// An absolute path passes through unchanged. Build it for the host OS so
	// the case stays valid on Windows, where "/tmp/x/..." is not absolute.
	absRoot := filepath.ToSlash(filepath.Join(t.TempDir(), "x", "..."))
	tests := []struct {
		root string
		want string
	}{
		{root: ".", want: "./..."},
		{root: "./...", want: "./..."},
		{root: "...", want: "./..."},
		{root: "./pkg/...", want: "./pkg/..."},
		{root: "pkg/...", want: "./pkg/..."},
		{root: "pkg", want: "./pkg/..."},
		{root: absRoot, want: absRoot},
	}
	for _, test := range tests {
		t.Run(test.root, func(t *testing.T) {
			t.Parallel()
			if got := cwdPattern(test.root); got != test.want {
				t.Errorf("cwdPattern(%q) = %q, want %q", test.root, got, test.want)
			}
		})
	}
}

// TestBufGenOutDirs covers which plugin out: directories become rewrite
// exclusions. A dedicated subdirectory (out: gen) is excluded, but an out: dir
// that contains the module itself (out: ., the source_relative layout that
// interleaves generated and hand-written files) must NOT be excluded. Excluding
// it marked the whole module as generated and hid every Go file.
func TestBufGenOutDirs(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name       string
		out        string
		wantLen    int
		wantSuffix string
	}{
		{name: "dedicated dir", out: "gen", wantLen: 1, wantSuffix: "/gen"},
		{name: "nested dir", out: "internal/gen", wantLen: 1, wantSuffix: "/internal/gen"},
		{name: "interleaved dot", out: ".", wantLen: 0},
		{name: "interleaved dot slash", out: "./", wantLen: 0},
		{name: "parent", out: "..", wantLen: 0},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			content := []byte("version: v2\nplugins:\n  - out: " + test.out + "\n")
			got := bufGenOutDirs(filepath.Join("proj", "buf.gen.yaml"), content)
			if len(got) != test.wantLen {
				t.Fatalf("bufGenOutDirs(out: %s) = %q, want %d dir(s)", test.out, got, test.wantLen)
			}
			if test.wantLen == 1 && !strings.HasSuffix(filepath.ToSlash(got[0]), test.wantSuffix) {
				t.Errorf("bufGenOutDirs(out: %s) = %q, want suffix %q", test.out, got[0], test.wantSuffix)
			}
		})
	}
}

// TestDiscoverTemplatesSkipsTestdata verifies that buf.gen.yaml files under a
// testdata directory are ignored: they are test fixtures, not real generation
// configs, and rewriting them would corrupt the fixtures.
func TestDiscoverTemplatesSkipsTestdata(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "buf.gen.yaml"), "version: v2\n")
	writeFile(t, filepath.Join(root, "testdata", "buf.gen.yaml"), "version: v2\n")

	templates, _, err := discoverTemplates([]string{root})
	if err != nil {
		t.Fatal(err)
	}
	if len(templates) != 1 {
		t.Fatalf("found %d templates, want 1 (testdata skipped)", len(templates))
	}
	if want := filepath.Join(root, "buf.gen.yaml"); templates[0].path != want {
		t.Errorf("returned %s, want the root template %s", templates[0].path, want)
	}
}

// TestUnderDir covers the main-module containment check used to classify
// no-module stub packages: a directory at or below the root is "under" it,
// while a sibling (even one sharing a name prefix) or a parent is not.
func TestUnderDir(t *testing.T) {
	t.Parallel()
	root := filepath.FromSlash("/home/u/proj")
	tests := []struct {
		path string
		want bool
	}{
		{path: filepath.FromSlash("/home/u/proj"), want: true},
		{path: filepath.FromSlash("/home/u/proj/gen/foo"), want: true},
		{path: filepath.FromSlash("/home/u/projector"), want: false}, // shared prefix, not nested
		{path: filepath.FromSlash("/home/u/other"), want: false},
		{path: filepath.FromSlash("/home/u"), want: false},
	}
	for _, test := range tests {
		if got := underDir(test.path, root); got != test.want {
			t.Errorf("underDir(%q, %q) = %v, want %v", test.path, root, got, test.want)
		}
	}
}

// TestCategorizeV1Stub covers the regenerate advice each kind of v1 stub package
// drives. The main module is local. A BSR connect SDK is a `go get @v2`. Another
// dependency is an external update. A package with no module attribution is local
// only when it lives inside the main module tree, not lumped in with the main
// module (which would tell the user to regenerate code they do not own).
func TestCategorizeV1Stub(t *testing.T) {
	t.Parallel()
	mainDir := t.TempDir()
	outsideDir := t.TempDir()
	pkg := func(mod *packages.Module, dir string) *packages.Package {
		return &packages.Package{Module: mod, CompiledGoFiles: []string{filepath.Join(dir, "stub.go")}}
	}

	local := map[string]bool{}
	sdk := map[string]bool{}
	external := map[string]bool{}
	categorizeV1Stub(pkg(&packages.Module{Main: true}, filepath.Join(mainDir, "gen")), 0, mainDir, local, sdk, external)
	categorizeV1Stub(pkg(&packages.Module{Path: "buf.build/gen/go/acme/api/connectrpc/go"}, mainDir), 0, mainDir, local, sdk, external)
	categorizeV1Stub(pkg(&packages.Module{Path: "github.com/acme/dep"}, outsideDir), 0, mainDir, local, sdk, external)
	categorizeV1Stub(pkg(nil, filepath.Join(mainDir, "vendored")), 0, mainDir, local, sdk, external) // no module, inside main
	categorizeV1Stub(pkg(nil, outsideDir), 0, mainDir, local, sdk, external)                         // no module, outside main

	if want := filepath.Join(mainDir, "gen"); !local[want] {
		t.Errorf("main-module stub dir %q not recorded as local: %v", want, local)
	}
	if want := filepath.Join(mainDir, "vendored"); !local[want] {
		t.Errorf("no-module stub under main %q not recorded as local: %v", want, local)
	}
	if local[outsideDir] {
		t.Errorf("no-module stub outside main must not be recorded as local: %v", local)
	}
	if !sdk["buf.build/gen/go/acme/api/connectrpc/go"] {
		t.Errorf("BSR connect SDK not recorded: %v", sdk)
	}
	if !external["github.com/acme/dep"] {
		t.Errorf("external dependency module not recorded: %v", external)
	}
}

// writeFile writes content to path, creating parent directories as needed.
func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

// TestResolveRoot covers resolving a root to its enclosing module and the
// pattern within it: pointing at a module directory (or a "..." wildcard over
// it) loads that module from its own root, and a subdirectory scopes the
// pattern under it. This is the behaviour that makes
// "connect-go-v2-migrate ./trivy" act like "cd trivy && connect-go-v2-migrate".
func TestResolveRoot(t *testing.T) {
	t.Parallel()
	// A module at module/ with a subpackage at module/sub/, none above it.
	module := t.TempDir()
	if err := os.WriteFile(filepath.Join(module, "go.mod"), []byte("module example.com/m\n\ngo 1.25\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(module, "sub"), 0o755); err != nil {
		t.Fatal(err)
	}

	tests := []struct {
		name        string
		root        string
		wantDir     string
		wantPattern string
	}{
		{name: "module dir", root: module, wantDir: module, wantPattern: "./..."},
		{name: "module wildcard", root: module + "/...", wantDir: module, wantPattern: "./..."},
		{name: "subdir", root: filepath.Join(module, "sub"), wantDir: module, wantPattern: "./sub/..."},
		{name: "subdir wildcard", root: module + "/sub/...", wantDir: module, wantPattern: "./sub/..."},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			dir, pattern := resolveRoot(test.root)
			if dir != test.wantDir || pattern != test.wantPattern {
				t.Errorf("resolveRoot(%q) = (%q, %q), want (%q, %q)", test.root, dir, pattern, test.wantDir, test.wantPattern)
			}
		})
	}
}

// TestWalkRoot covers the directory the template scan walks for a requested
// root: a "..." wildcard is reduced to the directory it spans, since it is not
// a real filesystem path.
func TestWalkRoot(t *testing.T) {
	t.Parallel()
	tests := []struct {
		root string
		want string
	}{
		{root: ".", want: "."},
		{root: "./...", want: "."},
		{root: "...", want: "."},
		{root: "pkg/...", want: "pkg"},
		{root: "./pkg/...", want: "pkg"},
		{root: "pkg", want: "pkg"},
		{root: "main.go", want: "main.go"},
	}
	for _, test := range tests {
		t.Run(test.root, func(t *testing.T) {
			t.Parallel()
			if got := walkRoot(test.root); got != test.want {
				t.Errorf("walkRoot(%q) = %q, want %q", test.root, got, test.want)
			}
		})
	}
}
