// Copyright 2021-2026 The Connect Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"go/ast"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"golang.org/x/mod/modfile"
	"golang.org/x/tools/go/packages"
)

const (
	generatedMarker = "DO NOT EDIT"
	// connectStubMarker identifies protoc-gen-connect-go output. Only these
	// stubs decide the regenerate-first phase; other connect importers (mocks)
	// do not.
	connectStubMarker = "protoc-gen-connect-go"
	connectV1Path     = "connectrpc.com/connect"
	// bsrModulePrefix is the BSR Go SDK import-path prefix:
	// buf.build/gen/go/<owner>/<module>/<plugin-owner>/<plugin>.
	bsrModulePrefix = "buf.build/gen/go/"
	// bsrConnectPlugin is the connect plugin's segment; only its output is
	// versioned with connect, so only it takes the @v2 query.
	bsrConnectPlugin = "/connectrpc/"
)

// isBSRConnectModule reports whether modulePath is a BSR Go SDK generated by the
// connect-go plugin, so `go get @v2` resolves to the connect-v2 build.
func isBSRConnectModule(modulePath string) bool {
	return strings.HasPrefix(modulePath, bsrModulePrefix) && strings.Contains(modulePath, bsrConnectPlugin)
}

// fileContent pairs a path with its bytes. ready is false when the source binds
// a stub still on v1, deferring its stub-dependent rewrites.
type fileContent struct {
	path    string
	content []byte
	ready   bool
}

// project is the result of discovering what to migrate.
type project struct {
	templates []fileContent // buf.gen.yaml / buf.gen.*.yaml
	sources   []fileContent // hand-written .go that uses connect (generated excluded)
	hasV1Gen  bool          // generated connect code (local or dependency) still imports v1
	v1GenDirs []string      // directories holding the main module's own v1 generated code
	// sdkModules are BSR-generated SDK dependencies still on v1; `go get @v2`
	// pulls the connect-v2 build.
	sdkModules []string
	// externalGenModules ship v1 generated connect code but have no reliable
	// version query, so they are surfaced as a caution.
	externalGenModules []string
	// ecosystemModules are the v2 paths for imported connectrpc.com satellites
	// (otelconnect, grpcreflect, ...).
	ecosystemModules []string
	// packagesLoaded is how many packages loaded Go syntax; zero means no module
	// loaded (run outside a module, or above nested modules).
	packagesLoaded int
	// goFilesScanned counts non-generated Go files examined, so the report can
	// tell "no Go code" from "Go code, none using connect".
	goFilesScanned int
	// nestedModuleDirs holds go.mod directories below the roots, populated only
	// when packagesLoaded is zero.
	nestedModuleDirs []string
	// handlerStreams resolves a handler RPC name to its generated v2 stream type.
	handlerStreams *handlerStreamResolver
	// mockV1Pkgs import connect v1 but are not connect stubs (mockery); their own
	// tool regenerates them, so they are a follow-up, not a blocker.
	mockV1Pkgs []string
	// goModRequires maps the main module's required module paths to versions,
	// used to advise a `go get` for v2 modules go.mod is missing. Nil when no
	// main module go.mod was found or parsed.
	goModRequires map[string]string
}

// discover loads the Go package graph and walks each package's import map: a
// file is a candidate when it imports connect directly or through a package that
// does. Generated code is never a source (the "DO NOT EDIT" marker or a
// buf.gen.yaml out: dir); a generated file still on v1 flips hasV1Gen. Buf
// templates are found with a filesystem walk.
func discover(roots []string) (project, error) {
	templates, genDirs, err := discoverTemplates(roots)
	if err != nil {
		return project{}, err
	}
	proj := project{templates: templates}

	mode := packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles |
		packages.NeedImports | packages.NeedDeps | packages.NeedSyntax |
		packages.NeedTypes | packages.NeedTypesInfo | packages.NeedModule
	// Tests:true so _test.go files (where most client streaming lives) are
	// rewritten too; the seen set below de-duplicates package variants.
	pkgs, err := loadGoPackages(roots, packages.Config{Mode: mode, Tests: true})
	if err != nil {
		return project{}, err
	}
	// Count packages that loaded Go syntax; zero means no Go code to migrate.
	for _, pkg := range pkgs {
		if len(pkg.Syntax) > 0 {
			proj.packagesLoaded++
		}
	}
	proj.goModRequires = mainModuleRequires(pkgs)
	// A handler implements its service interface without importing the generated
	// connect package, so cross-module stubs are absent from the closure above.
	// Pull in those dependency connect packages so their handler streams resolve.
	resolverPkgs := make([]*packages.Package, 0, len(pkgs))
	resolverPkgs = append(resolverPkgs, pkgs...)
	resolverPkgs = append(resolverPkgs, loadDependencyConnectPackages(pkgs, mode)...)
	proj.handlerStreams = buildHandlerStreamResolver(resolverPkgs)

	// Sweep the whole graph for packages that import connect and for generated
	// packages still on v1 (the blocker), categorizing the latter by module so
	// the regenerate advice fits.
	mainDir := mainModuleDir(pkgs)
	stubPkgs := map[string]bool{}
	v1StubPkgs := map[string]bool{}
	mockV1Pkgs := map[string]bool{}
	localGenDirs := map[string]bool{}
	sdkModules := map[string]bool{}
	externalGenModules := map[string]bool{}
	packages.Visit(pkgs, func(pkg *packages.Package) bool {
		if pkg.Imports[connectV1Path] != nil || pkg.Imports[connectV2Module] != nil {
			stubPkgs[pkg.PkgPath] = true
		}
		for index, file := range pkg.Syntax {
			if !fileImports(file, connectV1Path) {
				continue
			}
			// A v1 connect stub blocks its consumers until regeneration; a v1 mock
			// is a follow-up its own tool handles.
			switch {
			case isConnectStubAST(file):
				proj.hasV1Gen = true
				v1StubPkgs[pkg.PkgPath] = true
				categorizeV1Stub(pkg, index, mainDir, localGenDirs, sdkModules, externalGenModules)
			case isGeneratedAST(file):
				mockV1Pkgs[pkg.PkgPath] = true
			}
		}
		return true
	}, nil)

	// Collect rewrite candidates from the requested packages only (dependencies
	// are read, not edited), plus the ecosystem modules they import.
	ecosystem := map[string]bool{}
	seen := map[string]bool{}
	for _, pkg := range pkgs {
		for importPath := range pkg.Imports {
			if mod := ecosystemV2Module(importPath); mod != "" {
				ecosystem[mod] = true
			}
		}
		for index, file := range pkg.Syntax {
			if index >= len(pkg.CompiledGoFiles) {
				continue
			}
			path := pkg.CompiledGoFiles[index]
			if seen[path] {
				continue
			}
			seen[path] = true
			if isGeneratedAST(file) || underGenDir(path, genDirs) {
				continue
			}
			proj.goFilesScanned++
			// A file is a rewrite candidate if it uses connect or imports a
			// connectrpc.com ecosystem module (authn, grpchealth, ...): the
			// ecosystem reshape must reach files that import only a satellite.
			if !fileUsesConnect(file, stubPkgs) && !fileImportsEcosystem(file) {
				continue
			}
			content, readErr := os.ReadFile(path)
			if readErr != nil {
				return project{}, readErr
			}
			// Ready unless it binds a stub still on v1 (per stub package).
			proj.sources = append(proj.sources, fileContent{
				path:    path,
				content: content,
				ready:   !importsV1Stub(file, v1StubPkgs),
			})
		}
	}

	for pkg := range mockV1Pkgs {
		proj.mockV1Pkgs = append(proj.mockV1Pkgs, pkg)
	}
	sort.Strings(proj.mockV1Pkgs)

	for dir := range localGenDirs {
		proj.v1GenDirs = append(proj.v1GenDirs, dir)
	}
	for mod := range sdkModules {
		proj.sdkModules = append(proj.sdkModules, mod)
	}
	for mod := range externalGenModules {
		proj.externalGenModules = append(proj.externalGenModules, mod)
	}
	for mod := range ecosystem {
		proj.ecosystemModules = append(proj.ecosystemModules, mod)
	}
	sort.Strings(proj.sdkModules)
	sort.Strings(proj.externalGenModules)
	sort.Strings(proj.ecosystemModules)
	// No packages loaded: find nested modules to point the user at, since
	// "./..." stops at module boundaries.
	if proj.packagesLoaded == 0 {
		proj.nestedModuleDirs = findModuleDirs(roots)
	}
	sort.Strings(proj.v1GenDirs)
	sort.Slice(proj.sources, func(i, j int) bool { return proj.sources[i].path < proj.sources[j].path })
	return proj, nil
}

// categorizeV1Stub records where a v1 connect stub lives so the report can give
// the right regenerate advice: a local dir, a BSR SDK to `go get @v2`, or
// another dependency.
func categorizeV1Stub(pkg *packages.Package, index int, mainDir string, localGenDirs, sdkModules, externalGenModules map[string]bool) {
	switch {
	case pkg.Module != nil && pkg.Module.Main:
		if abs, ok := stubDir(pkg, index); ok {
			localGenDirs[abs] = true
		}
	case pkg.Module == nil:
		// No module attribution: treat as local only when inside the main module
		// tree; otherwise there is no module path to advise `go get @v2` on.
		if abs, ok := stubDir(pkg, index); ok && mainDir != "" && underDir(abs, mainDir) {
			localGenDirs[abs] = true
		}
	case isBSRConnectModule(pkg.Module.Path):
		sdkModules[pkg.Module.Path] = true
	default:
		externalGenModules[pkg.Module.Path] = true
	}
}

// mainModuleDir returns the main module's directory among pkgs, or "".
func mainModuleDir(pkgs []*packages.Package) string {
	if mod := mainModule(pkgs); mod != nil {
		return mod.Dir
	}
	return ""
}

// mainModule returns the main module of the loaded packages, or nil.
func mainModule(pkgs []*packages.Package) *packages.Module {
	for _, pkg := range pkgs {
		if pkg.Module != nil && pkg.Module.Main {
			return pkg.Module
		}
	}
	return nil
}

// mainModuleRequires parses the main module's go.mod and returns its required
// module paths and versions, or nil when it cannot be found or parsed.
func mainModuleRequires(pkgs []*packages.Package) map[string]string {
	mod := mainModule(pkgs)
	if mod == nil || mod.GoMod == "" {
		return nil
	}
	data, err := os.ReadFile(mod.GoMod)
	if err != nil {
		return nil
	}
	file, err := modfile.Parse(mod.GoMod, data, nil)
	if err != nil {
		return nil
	}
	requires := make(map[string]string, len(file.Require))
	for _, require := range file.Require {
		requires[require.Mod.Path] = require.Mod.Version
	}
	return requires
}

// stubDir returns the absolute directory of the stub package's file at index.
func stubDir(pkg *packages.Package, index int) (string, bool) {
	if index >= len(pkg.CompiledGoFiles) {
		return "", false
	}
	abs, err := filepath.Abs(filepath.Dir(pkg.CompiledGoFiles[index]))
	if err != nil {
		return "", false
	}
	return abs, true
}

// underDir reports whether path is dir itself or nested within it.
func underDir(path, dir string) bool {
	rel, err := filepath.Rel(dir, path)
	if err != nil {
		return false
	}
	return rel == "." || (rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator)))
}

// loadDependencyConnectPackages loads dependency modules that likely ship
// connect stubs absent from the import closure of pkgs (a replaced module or a
// BSR connect SDK), each as its own main module so its connect packages get
// full type information.
func loadDependencyConnectPackages(pkgs []*packages.Package, mode packages.LoadMode) []*packages.Package {
	dirs := map[string]bool{}
	packages.Visit(pkgs, func(pkg *packages.Package) bool {
		mod := pkg.Module
		if mod == nil || mod.Main {
			return true
		}
		// The connect library itself is never a source of user stubs; skip it so
		// a local replace of connect doesn't pull its internal test stubs into
		// the handler stream resolver.
		if mod.Path == connectV1Path || mod.Path == connectV2Module {
			return true
		}
		if mod.Replace == nil && !isBSRConnectModule(mod.Path) {
			return true
		}
		dir := mod.Dir
		if mod.Replace != nil && mod.Replace.Dir != "" {
			dir = mod.Replace.Dir
		}
		if dir != "" {
			dirs[dir] = true
		}
		return true
	}, nil)
	var out []*packages.Package
	for dir := range dirs {
		loaded, err := packages.Load(&packages.Config{Mode: mode, Dir: dir}, "./...")
		if err != nil {
			continue
		}
		out = append(out, loaded...)
	}
	return out
}

// buildHandlerStreamResolver scans loaded connect packages for generated handler
// stream types (<Service><RPC>ServerStream). The service prefix isn't in the
// handler signature, so this type-directed step supplies what the AST pass can't.
func buildHandlerStreamResolver(pkgs []*packages.Package) *handlerStreamResolver {
	resolver := &handlerStreamResolver{}
	seen := map[string]bool{}
	packages.Visit(pkgs, func(pkg *packages.Package) bool {
		if pkg.Types == nil || !strings.HasSuffix(pkg.PkgPath, "connect") {
			return true
		}
		scope := pkg.Types.Scope()
		for _, name := range scope.Names() {
			if !token.IsExported(name) || !strings.HasSuffix(name, "ServerStream") {
				continue
			}
			typeName, isType := scope.Lookup(name).(*types.TypeName)
			if !isType {
				continue
			}
			key := pkg.PkgPath + "." + name
			if seen[key] {
				continue
			}
			seen[key] = true
			named, isNamed := typeName.Type().(*types.Named)
			if !isNamed {
				continue
			}
			resolver.types = append(resolver.types, handlerStreamType{
				pkgPath:  pkg.PkgPath,
				pkgName:  pkg.Types.Name(),
				name:     name,
				messages: streamMessageNames(named),
			})
		}
		return true
	}, nil)
	return resolver
}

// streamMessageNames returns the sorted base names of the proto message types a
// generated stream type carries, read from the pointer params/results of its
// Send/Receive methods.
func streamMessageNames(named *types.Named) []string {
	set := map[string]bool{}
	for method := range named.Methods() {
		if method.Name() != "Send" && method.Name() != "Receive" {
			continue
		}
		sig, ok := method.Type().(*types.Signature)
		if !ok {
			continue
		}
		for _, tuple := range []*types.Tuple{sig.Params(), sig.Results()} {
			for variable := range tuple.Variables() {
				if ptr, ok := variable.Type().(*types.Pointer); ok {
					if elem, ok := ptr.Elem().(*types.Named); ok {
						set[elem.Obj().Name()] = true
					}
				}
			}
		}
	}
	names := make([]string, 0, len(set))
	for name := range set {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// findModuleDirs returns the directories holding go.mod files under the roots,
// used when packages.Load found nothing.
func findModuleDirs(roots []string) []string {
	seen := map[string]bool{}
	var dirs []string
	for _, root := range roots {
		_ = walkProject(walkRoot(root), func(path string) error {
			if filepath.Base(path) != "go.mod" {
				return nil
			}
			dir := filepath.Dir(path)
			if !seen[dir] {
				seen[dir] = true
				dirs = append(dirs, dir)
			}
			return nil
		})
	}
	sort.Strings(dirs)
	return dirs
}

// loadGoPackages loads the requested roots, each resolved to its enclosing
// module and loaded with that module as the working directory (so a nested
// module migrates as if run from inside it). Roots sharing a module load
// together. base is cloned per module with Dir filled in.
func loadGoPackages(roots []string, base packages.Config) ([]*packages.Package, error) {
	if len(roots) == 0 {
		roots = []string{"."}
	}
	patternsByDir := map[string][]string{}
	var dirOrder []string
	for _, root := range roots {
		dir, pattern := resolveRoot(root)
		if _, seen := patternsByDir[dir]; !seen {
			dirOrder = append(dirOrder, dir)
		}
		patternsByDir[dir] = append(patternsByDir[dir], pattern)
	}
	var all []*packages.Package
	for _, dir := range dirOrder {
		cfg := base // copy; Dir is per-module
		cfg.Dir = dir
		pkgs, err := packages.Load(&cfg, patternsByDir[dir]...)
		if err != nil {
			return nil, err
		}
		all = append(all, pkgs...)
	}
	return all, nil
}

// resolveRoot maps a root to its module directory and packages.Load pattern: a
// directory/"..." becomes a recursive pattern, a .go file a "file=" query. With
// no enclosing module the dir is "" so packages.Load reports it.
func resolveRoot(root string) (dir, pattern string) {
	if strings.HasSuffix(root, ".go") {
		abs, err := filepath.Abs(root)
		if err != nil {
			return "", root
		}
		return moduleDir(filepath.Dir(abs)), "file=" + abs
	}
	abs, err := filepath.Abs(walkRoot(root))
	if err != nil {
		return "", cwdPattern(root)
	}
	module := moduleDir(abs)
	if module == "" {
		return "", cwdPattern(root)
	}
	rel, err := filepath.Rel(module, abs)
	if err != nil {
		return "", cwdPattern(root)
	}
	if rel = filepath.ToSlash(rel); rel == "." {
		return module, "./..."
	}
	return module, "./" + rel + "/..."
}

// moduleDir returns the nearest ancestor of dir (inclusive) holding a go.mod.
func moduleDir(dir string) string {
	for {
		if info, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil && !info.IsDir() {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}

// cwdPattern maps a root to a packages.Load pattern relative to the current
// directory, rooting wildcards at "./" and making directories recursive.
func cwdPattern(root string) string {
	switch {
	case strings.Contains(root, "..."):
		root = filepath.ToSlash(root)
		if filepath.IsAbs(root) || strings.HasPrefix(root, "./") || strings.HasPrefix(root, "../") {
			return root
		}
		return "./" + root
	case root == ".":
		return "./..."
	default:
		clean := filepath.ToSlash(filepath.Clean(root))
		if !filepath.IsAbs(clean) && !strings.HasPrefix(clean, "./") {
			clean = "./" + clean
		}
		return clean + "/..."
	}
}

// walkRoot is the directory to walk for Buf templates: a "..." wildcard is
// reduced to the directory it spans, everything else walked as given.
func walkRoot(root string) string {
	if before, _, found := strings.Cut(root, "..."); found {
		return filepath.Clean(before) // Clean("") == ".", so "..." spans the cwd
	}
	return root
}

func fileImports(file *ast.File, importPath string) bool {
	for _, spec := range file.Imports {
		if path, err := strconv.Unquote(spec.Path.Value); err == nil && path == importPath {
			return true
		}
	}
	return false
}

// importsV1Stub reports whether the file imports a connect stub still on v1.
func importsV1Stub(file *ast.File, v1StubPkgs map[string]bool) bool {
	for _, spec := range file.Imports {
		if path, err := strconv.Unquote(spec.Path.Value); err == nil && v1StubPkgs[path] {
			return true
		}
	}
	return false
}

// fileUsesConnect reports whether the file imports connect directly or through a
// package that does, so stub-only usage is still caught.
// fileImportsEcosystem reports whether the file imports a connectrpc.com
// ecosystem module (authn, grpchealth, grpcreflect, vanguard, ...) that has a
// v2 migration, so its imports and call sites can be reshaped even when it does
// not import connect directly.
func fileImportsEcosystem(file *ast.File) bool {
	for _, spec := range file.Imports {
		path, err := strconv.Unquote(spec.Path.Value)
		if err != nil {
			continue
		}
		if ecosystemV2Module(path) != "" {
			return true
		}
	}
	return false
}

func fileUsesConnect(file *ast.File, stubPkgs map[string]bool) bool {
	for _, spec := range file.Imports {
		path, err := strconv.Unquote(spec.Path.Value)
		if err != nil {
			continue
		}
		if path == connectV1Path || path == connectV2Module || stubPkgs[path] {
			return true
		}
	}
	return false
}

func isGeneratedAST(file *ast.File) bool {
	return headerContains(file, generatedMarker)
}

func isConnectStubAST(file *ast.File) bool {
	return headerContains(file, connectStubMarker)
}

// headerContains reports whether a comment before the package clause has marker.
func headerContains(file *ast.File, marker string) bool {
	for _, group := range file.Comments {
		if group.End() > file.Package {
			break // past the header
		}
		if strings.Contains(group.Text(), marker) {
			return true
		}
	}
	return false
}

// discoverTemplates walks the roots for Buf templates, returning them and the
// absolute set of their plugin out: directories (excluded from rewriting).
func discoverTemplates(roots []string) ([]fileContent, map[string]bool, error) {
	var templates []fileContent
	genDirs := map[string]bool{}
	visited := map[string]bool{}
	for _, root := range roots {
		err := walkProject(walkRoot(root), func(path string) error {
			if !isBufGenFile(filepath.Base(path)) {
				return nil
			}
			abs, err := filepath.Abs(path)
			if err != nil {
				return err
			}
			if visited[abs] {
				return nil
			}
			visited[abs] = true
			content, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			templates = append(templates, fileContent{path: path, content: content})
			for _, dir := range bufGenOutDirs(path, content) {
				genDirs[dir] = true
			}
			return nil
		})
		if err != nil {
			return nil, nil, err
		}
	}
	return templates, genDirs, nil
}

// underGenDir reports whether path lives inside a buf.gen.yaml out: directory.
func underGenDir(path string, genDirs map[string]bool) bool {
	abs, err := filepath.Abs(path)
	if err != nil {
		return false
	}
	for dir := range genDirs {
		if abs != dir && dirContains(dir, abs) {
			return true
		}
	}
	return false
}

// bufGenOutDirs extracts a buf.gen.yaml's plugin out: directories as absolute
// paths relative to the template's directory. An out: dir that contains the
// template's own directory (the common `out: .` source_relative form) is
// dropped; those generated files are caught by their "DO NOT EDIT" marker.
func bufGenOutDirs(templatePath string, content []byte) []string {
	base, err := filepath.Abs(filepath.Dir(templatePath))
	if err != nil {
		return nil
	}
	var dirs []string
	for line := range strings.SplitSeq(string(content), "\n") {
		trimmed := strings.TrimSpace(line)
		// Match the plugin `out:` key in either `- out: gen` or `out: gen` form.
		trimmed = strings.TrimPrefix(trimmed, "- ")
		if !strings.HasPrefix(trimmed, "out:") {
			continue
		}
		value := yamlScalar(trimmed[len("out:"):])
		if value == "" {
			continue
		}
		abs, err := filepath.Abs(filepath.Join(base, value))
		if err != nil || dirContains(abs, base) {
			continue
		}
		dirs = append(dirs, abs)
	}
	return dirs
}

// dirContains reports whether outer is inner or an ancestor of it.
func dirContains(outer, inner string) bool {
	rel, err := filepath.Rel(outer, inner)
	if err != nil {
		return false
	}
	return rel == "." || (rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator)))
}
