// Copyright 2021-2026 The Connect Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"path"
	"strconv"
	"strings"

	"golang.org/x/tools/go/ast/astutil"
)

// RewriteSDKImports moves imports of v1 BSR connect SDKs to their v2 modules.
// It is the only Go edit made before the generated code is on v2.
func RewriteSDKImports(sdkModules []string) func(string, []byte) ([]byte, Report, error) {
	return func(filename string, src []byte) ([]byte, Report, error) {
		report := Report{}
		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, filename, src, parser.ParseComments)
		if err != nil {
			return nil, report, err
		}
		rewriteSDKImports(fset, file, sdkModules, &report)
		if !report.Changed {
			return src, report, nil
		}
		var buf bytes.Buffer
		if err := format.Node(&buf, fset, file); err != nil {
			return nil, report, err
		}
		return buf.Bytes(), report, nil
	}
}

// withSDKModules supplies the v1 BSR connect SDKs to move to v2.
func withSDKModules(sdkModules []string) rewriteOption {
	return func(state *rewriteState) { state.sdkModules = sdkModules }
}

func rewriteSDKImports(fset *token.FileSet, file *ast.File, sdkModules []string, report *Report) {
	var paths []string
	for _, spec := range file.Imports {
		if importPath, err := strconv.Unquote(spec.Path.Value); err == nil {
			paths = append(paths, importPath)
		}
	}
	for _, importPath := range paths {
		if target, ok := sdkV2Path(importPath, sdkModules); ok && astutil.RewriteImport(fset, file, importPath, target) {
			report.bump("import_sdk_v2")
		}
	}
}

// sdkV2Path returns the v2 import path of a package in a v1 BSR connect SDK.
func sdkV2Path(importPath string, sdkModules []string) (string, bool) {
	for _, mod := range sdkModules {
		rest, ok := strings.CutPrefix(importPath, mod)
		if ok && (rest == "" || strings.HasPrefix(rest, "/")) {
			return sdkV2Module(mod) + rest, true
		}
	}
	return "", false
}

// sdkV2Module returns the v2 module of a v1 BSR connect SDK. The v2 SDKs are
// generated by the go plugin, so gosimple SDKs move there too.
func sdkV2Module(mod string) string {
	return path.Dir(mod) + "/go/v2"
}
