version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - funlen
    - gocognit
    - inamedparam
    - ireturn
    - lll
    - maintidx
    - mnd
    - nlreturn
    - nonamedreturns
    - protogetter
    - testpackage
    - wrapcheck
    - wsl
  settings:
    errcheck:
      check-type-assertions: true
    exhaustruct:
      include:
        - connectrpc\.com/connect\..*[pP]arams
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print
        - pattern: ^log\.
        - pattern: ^print$
        - pattern: ^println$
        - pattern: ^panic$
    godox:
      keywords:
        - FIXME
    importas:
      alias:
        - pkg: connectrpc.com/connect/internal/gen/connect/ping/v1
          alias: pingv1
      no-unaliased: true
    varnamelen:
      ignore-decls:
        - T any
        - i int
        - wg sync.WaitGroup
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - exhaustive
        path: internal/assert/assert.go
      - linters:
          - containedctx
        path: duplex_http_call.go
      - linters:
          - gochecknoglobals
          - gochecknoinits
        path: example_init_test.go
      - linters:
          - ineffassign
        path: client_example_test.go
      - linters:
          - varnamelen
        path: cmd/protoc-gen-connect-go
        text: parameter name 'g' is too short
      - linters:
          - errcheck
          - gosec
        path: error_writer_example_test.go
      - linters:
          - revive
          - staticcheck
        path: client_example_test.go
      - linters:
          - gosec
          - testableexamples
        path: handler_example_test.go
      - linters:
          - testableexamples
        path: error_writer_example_test.go
      - linters:
          - testableexamples
        path: error_not_modified_example_test.go
      - linters:
          - testableexamples
        path: error_example_test.go
      - linters:
          - gosec
        path: error_not_modified_example_test.go
      - linters:
          - revive
        text: '^unused-parameter: '
      - linters:
          - revive
        path: protocol_grpc.go
        text: '^if-return: '
      - linters:
          - revive
        path: protocol_connect.go
        text: '^if-return: '
      - linters:
          - revive
        path: error_writer.go
        text: '^if-return: '
      - linters:
          - forbidigo
        path: internal/memhttp
        text: use of `log.(New|Logger|Lshortfile)` forbidden by pattern .*
      - linters:
          - noctx
        path: internal/memhttp/memhttp_test.go
      - linters:
          - perfsprint
        path: cmd/protoc-gen-connect-go/main.go
      - linters:
          - canonicalheader
        path: .*_test.go
      - linters:
          - recvcheck
        path: code.go
      - linters:
          - gosec
        path: .*_test.go
        text: '^G115: integer overflow conversion'
      - path: (.+)\.go$
        text: 'do not define dynamic errors, use wrapped static errors instead: .*'
formatters:
  enable:
    - gci
    - gofmt
  exclusions:
    generated: lax
