// Package rerpc is a small RPC framework built on protocol buffers and
// net/http. It's wire-compatible with gRPC and Twirp.
//
// Servers and clients built with this package use gRPC's HTTP/2 protocol, so
// they're compatible with any other gRPC implementation (including
// grpc-go, command-line tools like grpcurl, and proxies like gRPC-Gateway and
// Envoy).
//
// Servers built with this package also support Twirp's HTTP/1.1 protocol, so
// clients generated by any Twirp implementation can call reRPC servers. More
// importantly, Twirp's JSON variant is easy to use with cURL.
//
// This documentation is intended to explain each API in isolation. For
// walkthroughs, comparisons to grpc-go and Twirp, and other narrative docs,
// see the project wiki: https://github.com/akshayjshah/rerpc/wiki.
package rerpc
