// Code generated by protoc-gen-go-rerpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-rerpc v0.0.1
// - protoc             v3.17.3
// source: internal/crosstest/v1test/cross.proto

package crosspb

import (
	context "context"
	rerpc "github.com/akshayjshah/rerpc"
	proto "google.golang.org/protobuf/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the
// rerpc package are compatible. If you get a compiler error that this constant
// isn't defined, this code was generated with a version of rerpc newer than the
// one compiled into your binary. You can fix the problem by either regenerating
// this code with an older version of rerpc or updating the rerpc version
// compiled into your binary.
const _ = rerpc.SupportsCodeGenV0 // requires reRPC v0.0.1 or later

// CrossServiceClientReRPC is a client for the
// internal.crosstest.v1test.CrossService service.
type CrossServiceClientReRPC interface {
	Ping(ctx context.Context, req *PingRequest, opts ...rerpc.CallOption) (*PingResponse, error)
	Fail(ctx context.Context, req *FailRequest, opts ...rerpc.CallOption) (*FailResponse, error)
}

type crossServiceClientReRPC struct {
	ping rerpc.Client
	fail rerpc.Client
}

// NewCrossServiceClientReRPC constructs a client for the
// internal.crosstest.v1test.CrossService service. Call options passed here
// apply to all calls made with this client.
//
// The URL supplied here should be the base URL for the gRPC server (e.g.,
// https://api.acme.com or https://acme.com/api/grpc).
func NewCrossServiceClientReRPC(baseURL string, doer rerpc.Doer, opts ...rerpc.CallOption) CrossServiceClientReRPC {
	baseURL = strings.TrimRight(baseURL, "/")
	return &crossServiceClientReRPC{
		ping: *rerpc.NewClient(
			doer,
			baseURL+"/internal.crosstest.v1test.CrossService/Ping", // complete URL to call method
			"internal.crosstest.v1test.CrossService.Ping",          // fully-qualified protobuf method
			"internal.crosstest.v1test.CrossService",               // fully-qualified protobuf service
			"internal.crosstest.v1test",                            // fully-qualified protobuf package
			func() proto.Message { return &PingResponse{} },        // response constructor
			opts...,
		),
		fail: *rerpc.NewClient(
			doer,
			baseURL+"/internal.crosstest.v1test.CrossService/Fail", // complete URL to call method
			"internal.crosstest.v1test.CrossService.Fail",          // fully-qualified protobuf method
			"internal.crosstest.v1test.CrossService",               // fully-qualified protobuf service
			"internal.crosstest.v1test",                            // fully-qualified protobuf package
			func() proto.Message { return &FailResponse{} },        // response constructor
			opts...,
		),
	}
}

// Ping calls internal.crosstest.v1test.CrossService.Ping. Call options passed
// here apply only to this call.
func (c *crossServiceClientReRPC) Ping(ctx context.Context, req *PingRequest, opts ...rerpc.CallOption) (*PingResponse, error) {
	res, err := c.ping.Call(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return res.(*PingResponse), nil
}

// Fail calls internal.crosstest.v1test.CrossService.Fail. Call options passed
// here apply only to this call.
func (c *crossServiceClientReRPC) Fail(ctx context.Context, req *FailRequest, opts ...rerpc.CallOption) (*FailResponse, error) {
	res, err := c.fail.Call(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return res.(*FailResponse), nil
}

// CrossServiceReRPC is a server for the internal.crosstest.v1test.CrossService
// service. To make sure that adding methods to this protobuf service doesn't
// break all implementations of this interface, all implementations must embed
// UnimplementedCrossServiceReRPC.
//
// By default, recent versions of grpc-go have a similar forward compatibility
// requirement. See https://github.com/grpc/grpc-go/issues/3794 for a longer
// discussion.
type CrossServiceReRPC interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Fail(context.Context, *FailRequest) (*FailResponse, error)
	mustEmbedUnimplementedCrossServiceReRPC()
}

// NewCrossServiceHandlerReRPC wraps the service implementation in an HTTP
// handler. It returns the handler and the path on which to mount it.
func NewCrossServiceHandlerReRPC(svc CrossServiceReRPC, opts ...rerpc.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()

	ping := rerpc.NewHandler(
		"internal.crosstest.v1test.CrossService.Ping", // fully-qualified protobuf method
		"internal.crosstest.v1test.CrossService",      // fully-qualified protobuf service
		"internal.crosstest.v1test",                   // fully-qualified protobuf package
		rerpc.Func(func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typed, ok := req.(*PingRequest)
			if !ok {
				return nil, rerpc.Errorf(
					rerpc.CodeInternal,
					"error in generated code: expected req to be a *PingRequest, got a %T",
					req,
				)
			}
			return svc.Ping(ctx, typed)
		}),
		opts...,
	)
	mux.HandleFunc("/internal.crosstest.v1test.CrossService/Ping", func(w http.ResponseWriter, r *http.Request) {
		ping.Serve(w, r, &PingRequest{})
	})

	fail := rerpc.NewHandler(
		"internal.crosstest.v1test.CrossService.Fail", // fully-qualified protobuf method
		"internal.crosstest.v1test.CrossService",      // fully-qualified protobuf service
		"internal.crosstest.v1test",                   // fully-qualified protobuf package
		rerpc.Func(func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typed, ok := req.(*FailRequest)
			if !ok {
				return nil, rerpc.Errorf(
					rerpc.CodeInternal,
					"error in generated code: expected req to be a *FailRequest, got a %T",
					req,
				)
			}
			return svc.Fail(ctx, typed)
		}),
		opts...,
	)
	mux.HandleFunc("/internal.crosstest.v1test.CrossService/Fail", func(w http.ResponseWriter, r *http.Request) {
		fail.Serve(w, r, &FailRequest{})
	})

	// Respond to unknown protobuf methods with gRPC and Twirp's 404 equivalents.
	mux.Handle("/", rerpc.NewBadRouteHandler(opts...))

	return "/internal.crosstest.v1test.CrossService/", mux
}

var _ CrossServiceReRPC = (*UnimplementedCrossServiceReRPC)(nil) // verify interface implementation

// UnimplementedCrossServiceReRPC returns CodeUnimplemented from all methods. To
// maintain forward compatibility, all implementations of CrossServiceReRPC must
// embed UnimplementedCrossServiceReRPC.
type UnimplementedCrossServiceReRPC struct{}

func (UnimplementedCrossServiceReRPC) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, rerpc.Errorf(rerpc.CodeUnimplemented, "internal.crosstest.v1test.CrossService.Ping isn't implemented")
}

func (UnimplementedCrossServiceReRPC) Fail(context.Context, *FailRequest) (*FailResponse, error) {
	return nil, rerpc.Errorf(rerpc.CodeUnimplemented, "internal.crosstest.v1test.CrossService.Fail isn't implemented")
}

func (UnimplementedCrossServiceReRPC) mustEmbedUnimplementedCrossServiceReRPC() {}
