// Code generated by protoc-gen-go-rerpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-rerpc v0.0.1
// - protoc             v3.17.3
// source: internal/ping/v1test/ping.proto

package pingpb

import (
	context "context"
	rerpc "github.com/rerpc/rerpc"
	proto "google.golang.org/protobuf/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the
// rerpc package are compatible. If you get a compiler error that this constant
// isn't defined, this code was generated with a version of rerpc newer than the
// one compiled into your binary. You can fix the problem by either regenerating
// this code with an older version of rerpc or updating the rerpc version
// compiled into your binary.
const _ = rerpc.SupportsCodeGenV0 // requires reRPC v0.0.1 or later

// PingServiceClientReRPC is a client for the internal.ping.v1test.PingService
// service.
type PingServiceClientReRPC interface {
	Ping(ctx context.Context, req *PingRequest, opts ...rerpc.CallOption) (*PingResponse, error)
	Fail(ctx context.Context, req *FailRequest, opts ...rerpc.CallOption) (*FailResponse, error)
}

type pingServiceClientReRPC struct {
	ping rerpc.Client
	fail rerpc.Client
}

// NewPingServiceClientReRPC constructs a client for the
// internal.ping.v1test.PingService service. Call options passed here apply to
// all calls made with this client.
//
// The URL supplied here should be the base URL for the gRPC server (e.g.,
// https://api.acme.com or https://acme.com/api/grpc).
func NewPingServiceClientReRPC(baseURL string, doer rerpc.Doer, opts ...rerpc.CallOption) PingServiceClientReRPC {
	baseURL = strings.TrimRight(baseURL, "/")
	return &pingServiceClientReRPC{
		ping: *rerpc.NewClient(
			doer,
			baseURL+"/internal.ping.v1test.PingService/Ping", // complete URL to call method
			"internal.ping.v1test.PingService.Ping",          // fully-qualified protobuf method
			"internal.ping.v1test.PingService",               // fully-qualified protobuf service
			"internal.ping.v1test",                           // fully-qualified protobuf package
			func() proto.Message { return &PingResponse{} },  // response constructor
			opts...,
		),
		fail: *rerpc.NewClient(
			doer,
			baseURL+"/internal.ping.v1test.PingService/Fail", // complete URL to call method
			"internal.ping.v1test.PingService.Fail",          // fully-qualified protobuf method
			"internal.ping.v1test.PingService",               // fully-qualified protobuf service
			"internal.ping.v1test",                           // fully-qualified protobuf package
			func() proto.Message { return &FailResponse{} },  // response constructor
			opts...,
		),
	}
}

// Ping calls internal.ping.v1test.PingService.Ping. Call options passed here
// apply only to this call.
func (c *pingServiceClientReRPC) Ping(ctx context.Context, req *PingRequest, opts ...rerpc.CallOption) (*PingResponse, error) {
	res, err := c.ping.Call(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return res.(*PingResponse), nil
}

// Fail calls internal.ping.v1test.PingService.Fail. Call options passed here
// apply only to this call.
func (c *pingServiceClientReRPC) Fail(ctx context.Context, req *FailRequest, opts ...rerpc.CallOption) (*FailResponse, error) {
	res, err := c.fail.Call(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return res.(*FailResponse), nil
}

// PingServiceReRPC is a server for the internal.ping.v1test.PingService
// service. To make sure that adding methods to this protobuf service doesn't
// break all implementations of this interface, all implementations must embed
// UnimplementedPingServiceReRPC.
//
// By default, recent versions of grpc-go have a similar forward compatibility
// requirement. See https://github.com/grpc/grpc-go/issues/3794 for a longer
// discussion.
type PingServiceReRPC interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Fail(context.Context, *FailRequest) (*FailResponse, error)
	mustEmbedUnimplementedPingServiceReRPC()
}

// NewPingServiceHandlerReRPC wraps the service implementation in an HTTP
// handler. It returns the handler and the path on which to mount it.
func NewPingServiceHandlerReRPC(svc PingServiceReRPC, opts ...rerpc.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()

	ping := rerpc.NewHandler(
		"internal.ping.v1test.PingService.Ping", // fully-qualified protobuf method
		"internal.ping.v1test.PingService",      // fully-qualified protobuf service
		"internal.ping.v1test",                  // fully-qualified protobuf package
		rerpc.Func(func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typed, ok := req.(*PingRequest)
			if !ok {
				return nil, rerpc.Errorf(
					rerpc.CodeInternal,
					"error in generated code: expected req to be a *PingRequest, got a %T",
					req,
				)
			}
			return svc.Ping(ctx, typed)
		}),
		opts...,
	)
	mux.HandleFunc("/internal.ping.v1test.PingService/Ping", func(w http.ResponseWriter, r *http.Request) {
		ping.Serve(w, r, &PingRequest{})
	})

	fail := rerpc.NewHandler(
		"internal.ping.v1test.PingService.Fail", // fully-qualified protobuf method
		"internal.ping.v1test.PingService",      // fully-qualified protobuf service
		"internal.ping.v1test",                  // fully-qualified protobuf package
		rerpc.Func(func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typed, ok := req.(*FailRequest)
			if !ok {
				return nil, rerpc.Errorf(
					rerpc.CodeInternal,
					"error in generated code: expected req to be a *FailRequest, got a %T",
					req,
				)
			}
			return svc.Fail(ctx, typed)
		}),
		opts...,
	)
	mux.HandleFunc("/internal.ping.v1test.PingService/Fail", func(w http.ResponseWriter, r *http.Request) {
		fail.Serve(w, r, &FailRequest{})
	})

	// Respond to unknown protobuf methods with gRPC and Twirp's 404 equivalents.
	mux.Handle("/", rerpc.NewBadRouteHandler(opts...))

	return "/internal.ping.v1test.PingService/", mux
}

var _ PingServiceReRPC = (*UnimplementedPingServiceReRPC)(nil) // verify interface implementation

// UnimplementedPingServiceReRPC returns CodeUnimplemented from all methods. To
// maintain forward compatibility, all implementations of PingServiceReRPC must
// embed UnimplementedPingServiceReRPC.
type UnimplementedPingServiceReRPC struct{}

func (UnimplementedPingServiceReRPC) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, rerpc.Errorf(rerpc.CodeUnimplemented, "internal.ping.v1test.PingService.Ping isn't implemented")
}

func (UnimplementedPingServiceReRPC) Fail(context.Context, *FailRequest) (*FailResponse, error) {
	return nil, rerpc.Errorf(rerpc.CodeUnimplemented, "internal.ping.v1test.PingService.Fail isn't implemented")
}

func (UnimplementedPingServiceReRPC) mustEmbedUnimplementedPingServiceReRPC() {}
