// Code generated by protoc-gen-go-rerpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-rerpc v0.0.1
// - protoc             v3.17.3
// source: internal/pingpb/ping.proto

package pingpb

import (
	context "context"
	http "net/http"
	strings "strings"

	rerpc "github.com/akshayjshah/rerpc"
	proto "google.golang.org/protobuf/proto"
)

// This is a compile-time assertion to ensure that this generated file and the
// rerpc package are compatible. If you get a compiler error that this constant
// isn't defined, this code was generated with a version of rerpc newer than the
// one compiled into your binary. You can fix the problem by either regenerating
// this code with an older version of rerpc or updating the rerpc version
// compiled into your binary.
const _ = rerpc.SupportsCodeGenV0 // requires reRPC v0.0.1 or later

// PingClientReRPC is a client for the rerpc.internal.ping.v0.Ping service.
type PingClientReRPC interface {
	Ping(ctx context.Context, req *PingRequest, opts ...rerpc.CallOption) (*PingResponse, error)
	Fail(ctx context.Context, req *FailRequest, opts ...rerpc.CallOption) (*FailResponse, error)
}

type pingClientReRPC struct {
	ping rerpc.Client
	fail rerpc.Client
}

// NewPingClientReRPC constructs a client for the rerpc.internal.ping.v0.Ping
// service. Call options passed here apply to all calls made with this client.
//
// The URL supplied here should be the base URL for the gRPC server (e.g.,
// https://api.acme.com or https://acme.com/api/grpc).
func NewPingClientReRPC(baseURL string, doer rerpc.Doer, opts ...rerpc.CallOption) PingClientReRPC {
	baseURL = strings.TrimRight(baseURL, "/")
	return &pingClientReRPC{
		ping: *rerpc.NewClient(
			doer,
			baseURL+"/rerpc.internal.ping.v0.Ping/Ping", // complete URL to call method
			"rerpc.internal.ping.v0.Ping.Ping",          // fully-qualified protobuf method
			"rerpc.internal.ping.v0.Ping",               // fully-qualified protobuf service
			"rerpc.internal.ping.v0",                    // fully-qualified protobuf package
			opts...,
		),
		fail: *rerpc.NewClient(
			doer,
			baseURL+"/rerpc.internal.ping.v0.Ping/Fail", // complete URL to call method
			"rerpc.internal.ping.v0.Ping.Fail",          // fully-qualified protobuf method
			"rerpc.internal.ping.v0.Ping",               // fully-qualified protobuf service
			"rerpc.internal.ping.v0",                    // fully-qualified protobuf package
			opts...,
		),
	}
}

// Ping calls rerpc.internal.ping.v0.Ping.Ping. Call options passed here apply
// only to this call.
func (c *pingClientReRPC) Ping(ctx context.Context, req *PingRequest, opts ...rerpc.CallOption) (*PingResponse, error) {
	res := &PingResponse{}
	if err := c.ping.Call(ctx, req, res, opts...); err != nil {
		return nil, err
	}
	return res, nil
}

// Fail calls rerpc.internal.ping.v0.Ping.Fail. Call options passed here apply
// only to this call.
func (c *pingClientReRPC) Fail(ctx context.Context, req *FailRequest, opts ...rerpc.CallOption) (*FailResponse, error) {
	res := &FailResponse{}
	if err := c.fail.Call(ctx, req, res, opts...); err != nil {
		return nil, err
	}
	return res, nil
}

// PingServerReRPC is a server for the rerpc.internal.ping.v0.Ping service. To
// make sure that adding methods to this protobuf service doesn't break all
// implementations of this interface, all implementations must embed
// UnimplementedPingServerReRPC.
//
// By default, recent versions of grpc-go have a similar forward compatibility
// requirement. See https://github.com/grpc/grpc-go/issues/3794 for a longer
// discussion.
type PingServerReRPC interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Fail(context.Context, *FailRequest) (*FailResponse, error)
	mustEmbedUnimplementedPingServerReRPC()
}

// NewPingHandlerReRPC wraps the service implementation in an HTTP handler. It
// returns the handler and the path on which to mount it.
func NewPingHandlerReRPC(svc PingServerReRPC, opts ...rerpc.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()

	ping := rerpc.NewHandler(
		"rerpc.internal.ping.v0.Ping.Ping", // fully-qualified protobuf method
		"rerpc.internal.ping.v0.Ping",      // fully-qualified protobuf service
		"rerpc.internal.ping.v0",           // fully-qualified protobuf package
		rerpc.UnaryHandler(func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typed, ok := req.(*PingRequest)
			if !ok {
				return nil, rerpc.Errorf(
					rerpc.CodeInternal,
					"error in generated code: expected req to be a *PingRequest, got a %T",
					req,
				)
			}
			return svc.Ping(ctx, typed)
		}),
		opts...,
	)
	mux.HandleFunc("/rerpc.internal.ping.v0.Ping/Ping", func(w http.ResponseWriter, r *http.Request) {
		ping.Serve(w, r, &PingRequest{})
	})

	fail := rerpc.NewHandler(
		"rerpc.internal.ping.v0.Ping.Fail", // fully-qualified protobuf method
		"rerpc.internal.ping.v0.Ping",      // fully-qualified protobuf service
		"rerpc.internal.ping.v0",           // fully-qualified protobuf package
		rerpc.UnaryHandler(func(ctx context.Context, req proto.Message) (proto.Message, error) {
			typed, ok := req.(*FailRequest)
			if !ok {
				return nil, rerpc.Errorf(
					rerpc.CodeInternal,
					"error in generated code: expected req to be a *FailRequest, got a %T",
					req,
				)
			}
			return svc.Fail(ctx, typed)
		}),
		opts...,
	)
	mux.HandleFunc("/rerpc.internal.ping.v0.Ping/Fail", func(w http.ResponseWriter, r *http.Request) {
		fail.Serve(w, r, &FailRequest{})
	})

	// Respond to unknown protobuf methods with gRPC and Twirp's 404 equivalents.
	mux.Handle("/", rerpc.NewBadRouteHandler(opts...))

	return "/rerpc.internal.ping.v0.Ping/", mux
}

var _ PingServerReRPC = (*UnimplementedPingServerReRPC)(nil) // verify interface implementation

// UnimplementedPingServerReRPC returns CodeUnimplemented from all methods. To
// maintain forward compatibility, all implementations of PingServerReRPC must
// embed UnimplementedPingServerReRPC.
type UnimplementedPingServerReRPC struct{}

func (UnimplementedPingServerReRPC) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, rerpc.Errorf(rerpc.CodeUnimplemented, "method Ping not implemented")
}

func (UnimplementedPingServerReRPC) Fail(context.Context, *FailRequest) (*FailResponse, error) {
	return nil, rerpc.Errorf(rerpc.CodeUnimplemented, "method Fail not implemented")
}

func (UnimplementedPingServerReRPC) mustEmbedUnimplementedPingServerReRPC() {}
