// Code generated by protoc-gen-go-rerpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-rerpc v0.0.1
// - protoc             v3.17.3
// source: internal/reflection/v1alpha1/reflection.proto

package reflectionpb

import (
	context "context"
	errors "errors"
	rerpc "github.com/rerpc/rerpc"
	callstream "github.com/rerpc/rerpc/callstream"
	handlerstream "github.com/rerpc/rerpc/handlerstream"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the
// rerpc package are compatible. If you get a compiler error that this constant
// isn't defined, this code was generated with a version of rerpc newer than the
// one compiled into your binary. You can fix the problem by either regenerating
// this code with an older version of rerpc or updating the rerpc version
// compiled into your binary.
const _ = rerpc.SupportsCodeGenV0 // requires reRPC v0.0.1 or later

// ServerReflectionClientReRPC is a client for the
// internal.reflection.v1alpha1.ServerReflection service.
type ServerReflectionClientReRPC interface {
	// The reflection service is structured as a bidirectional stream, ensuring
	// all related requests go to a single server.
	ServerReflectionInfo(ctx context.Context) *callstream.Bidirectional[ServerReflectionRequest, ServerReflectionResponse]
}

type serverReflectionClientReRPC struct {
	doer    rerpc.Doer
	baseURL string
	options []rerpc.ClientOption
}

// NewServerReflectionClientReRPC constructs a client for the
// internal.reflection.v1alpha1.ServerReflection service.
//
// The URL supplied here should be the base URL for the gRPC server (e.g.,
// https://api.acme.com or https://acme.com/grpc).
func NewServerReflectionClientReRPC(baseURL string, doer rerpc.Doer, opts ...rerpc.ClientOption) ServerReflectionClientReRPC {
	return &serverReflectionClientReRPC{
		baseURL: strings.TrimRight(baseURL, "/"),
		doer:    doer,
		options: opts,
	}
}

// ServerReflectionInfo calls
// internal.reflection.v1alpha1.ServerReflection.ServerReflectionInfo.
func (c *serverReflectionClientReRPC) ServerReflectionInfo(ctx context.Context) *callstream.Bidirectional[ServerReflectionRequest, ServerReflectionResponse] {
	call := rerpc.NewClientStream(
		c.doer,
		rerpc.StreamTypeBidirectional,
		c.baseURL,
		"internal.reflection.v1alpha1", // protobuf package
		"ServerReflection",             // protobuf service
		"ServerReflectionInfo",         // protobuf method
		c.options...,
	)
	_, stream := call(ctx)
	return callstream.NewBidirectional[ServerReflectionRequest, ServerReflectionResponse](stream)
}

// ServerReflectionReRPC is a server for the
// internal.reflection.v1alpha1.ServerReflection service.
type ServerReflectionReRPC interface {
	// The reflection service is structured as a bidirectional stream, ensuring
	// all related requests go to a single server.
	ServerReflectionInfo(context.Context, *handlerstream.Bidirectional[ServerReflectionRequest, ServerReflectionResponse]) error
}

// NewServerReflectionHandlerReRPC wraps each method on the service
// implementation in a *rerpc.Handler. The returned slice can be passed to
// rerpc.NewServeMux.
func NewServerReflectionHandlerReRPC(svc ServerReflectionReRPC, opts ...rerpc.HandlerOption) []*rerpc.Handler {
	handlers := make([]*rerpc.Handler, 0, 1)

	serverReflectionInfo := rerpc.NewStreamingHandler(
		rerpc.StreamTypeBidirectional,
		"internal.reflection.v1alpha1", // protobuf package
		"ServerReflection",             // protobuf service
		"ServerReflectionInfo",         // protobuf method
		func(ctx context.Context, stream rerpc.Stream) {
			typed := handlerstream.NewBidirectional[ServerReflectionRequest, ServerReflectionResponse](stream)
			err := svc.ServerReflectionInfo(ctx, typed)
			_ = stream.CloseReceive()
			if err != nil {
				if _, ok := rerpc.AsError(err); !ok {
					if errors.Is(err, context.Canceled) {
						err = rerpc.Wrap(rerpc.CodeCanceled, err)
					}
					if errors.Is(err, context.DeadlineExceeded) {
						err = rerpc.Wrap(rerpc.CodeDeadlineExceeded, err)
					}
				}
			}
			_ = stream.CloseSend(err)
		},
		opts...,
	)
	handlers = append(handlers, serverReflectionInfo)

	return handlers
}

var _ ServerReflectionReRPC = (*UnimplementedServerReflectionReRPC)(nil) // verify interface implementation

// UnimplementedServerReflectionReRPC returns CodeUnimplemented from all
// methods.
type UnimplementedServerReflectionReRPC struct{}

func (UnimplementedServerReflectionReRPC) ServerReflectionInfo(context.Context, *handlerstream.Bidirectional[ServerReflectionRequest, ServerReflectionResponse]) error {
	return rerpc.Errorf(rerpc.CodeUnimplemented, "internal.reflection.v1alpha1.ServerReflection.ServerReflectionInfo isn't implemented")
}
